import { triageMigrations } from "../src/triage-schema.js"
import { URL } from "node:url"
import { apiKeyMigrations } from "../src/api-key-schema.js"
import { readFile, writeFile, mkdir } from "node:fs/promises"
import openapiTS, { astToString, type OpenAPI3 } from "openapi-typescript"
import { developerOperations, inputJsonSchema, openApiDocument } from "../src/developer-contract.js"
const root = new URL("../../../", import.meta.url)
const document = openApiDocument()
const generated = "// Generated by pnpm api:generate. Do not edit.\n"
const manifest = Object.fromEntries(Object.entries(developerOperations).map(([id, o]) => [id, {
  method: o.method, path: o.path, scope: o.scope, description: o.description, inputSchema: inputJsonSchema(o.input.strict()),
}]))
const types = astToString(await openapiTS(document as unknown as OpenAPI3))
const files = {
  "ops/email/triage.sql": "-- Apply after developer-api.sql as the schema owner.\nBEGIN;\nSET LOCAL ROLE postgres;\n" + triageMigrations.join(";\n\n") + ";\nCOMMIT;\n",
  "ops/email/developer-api.sql": "-- Apply after inbox-onboarding.sql as the schema owner, with migration approval.\nBEGIN;\nSET LOCAL ROLE postgres;\n" + apiKeyMigrations.join(";\n\n") + ";\nCOMMIT;\n",
  "docs/openapi.json": JSON.stringify(document, null, 2) + "\n",
  "packages/email-sdk/src/operations.ts": generated + types,
  "packages/email-sdk/src/manifest.ts": generated + "export const manifest = " + JSON.stringify(manifest, null, 2) + " as const\n",
  "packages/email-python/bezalel_email/manifest.json": JSON.stringify(manifest, null, 2) + "\n",
}
for (const [path, content] of Object.entries(files)) {
  const url = new URL(path, root)
  if (process.argv.includes("--check")) {
    if (await readFile(url, "utf8") !== content) throw new Error(`Regenerate ${path} with pnpm api:generate`)
  } else { await mkdir(new URL(".", url), { recursive: true }); await writeFile(url, content) }
}
console.log(`${Object.keys(manifest).length} operations; OpenAPI, SDK types, CLI/MCP schemas, and Python manifest agree.`)
