import assert from 'node:assert/strict'
import { test } from 'node:test'

const base = process.env.DASHBOARD_TEST_URL ?? 'http://127.0.0.1:3190'
const control = process.env.DASHBOARD_TEST_CONTROL_URL ?? 'http://127.0.0.1:3191'
for (const value of [base, control]) { const url = new URL(value); assert.equal(url.protocol, 'http:'); assert.equal(url.hostname, '127.0.0.1') }
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright')

test('resource navigation, grouped inbox search, pagination, and deletion stay scoped to the chosen inbox', { timeout: 120_000 }, async t => {
  const browser = await chromium.launch({ ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}), args: ['--no-sandbox'] })
  let release = () => {}
  t.after(async () => { release(); await browser.close() })
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } }), page = await context.newPage(), errors = []
  page.on('pageerror', error => errors.push(error.message))
  const suffix = crypto.randomUUID().slice(0, 8), email = `console-${suffix}@example.net`
  const api = (operation, data = {}) => context.request.post(base + '/api/rpc/' + operation, { headers: { origin: base }, data })
  assert.equal((await context.request.post(base + '/api/auth/email-otp/send-verification-otp', { headers: { origin: base }, data: { email, type: 'sign-in' } })).status(), 200)
  const sent = await (await context.request.get(control + '/sends')).json()
  const otp = sent.filter(message => message.to.includes(email)).at(-1).text.match(/\b\d{6}\b/)[0]
  assert.equal((await context.request.post(base + '/api/auth/sign-in/email-otp', { headers: { origin: base }, data: { email, otp, name: 'Console regression' } })).status(), 200)
  const inboxes = []
  for (let i = 0; i < 12; i++) {
    const response = await api('createInbox', { username: `console-${suffix}-${i}`, displayName: `Agent ${i + 1}`, group: i < 2 ? 'research' : 'support' })
    assert.equal(response.status(), 200); inboxes.push((await response.json()).result)
  }
  await page.route('**/api/rpc/listInboxes', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Fixture inventory unavailable' }) }))
  await page.goto(base + '/app')
  await page.getByText('Fixture inventory unavailable', { exact: true }).waitFor()
  assert.equal(await page.locator('#inboxes-empty').isVisible(), false)
  await page.locator('#developers').click()
  await page.getByText('No account API keys yet.', { exact: true }).waitFor()
  await page.locator('[data-page=inboxes]').click()
  await page.unroute('**/api/rpc/listInboxes')
  await page.locator('#refresh-inboxes').click()
  await page.waitForFunction(() => document.querySelectorAll('#inbox-rows tr').length === 10)
  assert.equal(await page.locator('#mail-page').isVisible(), false)
  assert.equal(await page.locator('#sidebar').getByText(/Delete/).count(), 0)
  assert.equal(await page.locator('#inbox-count').textContent(), '12 inboxes')
  await page.locator('#inbox-next').click()
  assert.equal(await page.locator('#inbox-rows tr').count(), 2)
  await page.locator('#inbox-group').selectOption('research')
  assert.equal(await page.locator('#inbox-rows tr').count(), 2)
  assert.equal(await page.locator('#inbox-page-count').textContent(), 'Page 1 of 1')
  await page.locator('#inbox-search').fill('Agent 2')
  assert.equal(await page.locator('#inbox-rows tr').count(), 1)
  await page.locator('#inbox-rows a').click()
  await page.locator('#mail-page').waitFor()
  await page.waitForFunction(id => document.querySelector('#inboxes').value === id, inboxes[1].inboxId)
  assert.equal(await page.locator('#triage-filters').isVisible(), false)
  await page.locator('#toggle-triage').click()
  assert.equal(await page.locator('#triage-filters').isVisible(), true)
  await page.locator('#inboxes').selectOption(inboxes[0].inboxId)
  await page.waitForFunction(() => document.querySelector('#mail-heading').textContent === 'Agent 1')
  await page.reload()
  await page.waitForFunction(() => document.querySelector('#mail-heading').textContent === 'Agent 1')
  await page.locator('.back-link').click()
  await page.locator('#inboxes-page').waitFor()
  await page.goBack()
  await page.locator('#mail-page').waitFor()
  const setupRequests = []
  const trackSetup = request => { if (new URL(request.url()).pathname === '/api/rpc/setupStatus') setupRequests.push(request.postDataJSON().inboxId) }
  page.on('request', trackSetup)
  for (const openSetup of [() => page.locator('#get-started').click(), () => page.reload()]) {
    setupRequests.length = 0
    const response = page.waitForResponse('**/api/rpc/setupStatus')
    await openSetup()
    const result = await response
    assert.equal(result.status(), 200)
    await result.finished()
    await page.locator('#setup-address').filter({ hasText: inboxes[0].inboxId }).waitFor()
    assert.deepEqual(setupRequests, [inboxes[0].inboxId], 'Opening or reloading setup fetches its inbox status once')
  }
  page.off('request', trackSetup)
  await page.locator('#setup-dismiss').click()
  await page.locator('#mail-page').waitFor()
  await page.locator('#developers').click()
  await page.getByText('No account API keys yet.', { exact: true }).waitFor()
  assert.equal(await page.locator('#developer-dialog').isVisible(), false)
  await page.locator('#new-api-key').click()
  await page.locator('#developer-form [name=name]').fill('Console test key')
  await page.locator('#developer-create').click()
  await page.waitForFunction(() => document.querySelector('#developer-token').value.startsWith('bze_'))
  assert.equal(await page.locator('#developer-token').getAttribute('type'), 'password')
  await page.getByRole('button', { name: 'Close API key creation', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('#developer-token').value === '')
  await page.getByRole('button', { name: 'Revoke Console test key' }).waitFor()
  await page.locator('#integrations').click()
  await page.locator('#integrations-page').waitFor()
  assert.ok((await page.locator('#developer-mcp-url').textContent()).endsWith('/mcp'))
  await page.locator('[data-page=inboxes]').click()
  await page.locator('#inboxes-page').waitFor()
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `page overflow at ${width}`)
    assert.equal(await page.locator('.workspace-content').evaluate(e => e.scrollWidth > e.clientWidth), false, `content overflow at ${width}`)
  }
  for (const width of [320, 390, 767]) {
    await page.setViewportSize({ width, height: 844 })
    const open = await page.locator('#open-menu').boundingBox()
    assert.ok(open.width >= 44 && open.height >= 44, `Navigation opener has a 44px tap target at ${width}px`)
    await page.locator('#open-menu').click()
    const drawer = await page.locator('#sidebar').boundingBox()
    assert.equal(await page.locator('#logout').isVisible(), false, `the account menu starts closed at ${width}px`)
    await page.locator('#account-button').click()
    for (const selector of ['#close-menu', '#account-button', '#account-settings', '#logout']) {
      const bounds = await page.locator(selector).boundingBox()
      assert.ok(bounds.width >= 44 && bounds.height >= 44, `${selector} has a 44px tap target at ${width}px`)
      assert.ok(bounds.x >= drawer.x && bounds.x + bounds.width <= drawer.x + drawer.width, `${selector} fits inside the drawer at ${width}px`)
    }
    await page.locator('#account-button').click()
    assert.equal(await page.locator('#logout').isVisible(), false, `the account button closes its menu at ${width}px`)
    const close = await page.locator('#close-menu').boundingBox()
    await page.locator('#close-menu').click({ position: { x: close.width - 2, y: close.height / 2 } })
    assert.equal(await page.locator('#sidebar').evaluate(e => e.inert), true)
    assert.equal(await page.locator('#open-menu').evaluate(e => e === document.activeElement), true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('#open-menu').click()
  await page.locator('#integrations').click()
  await page.locator('#integrations-page').waitFor()
  assert.equal(await page.locator('#sidebar').evaluate(e => e.inert), true)
  assert.equal(await page.locator('.workspace').evaluate(e => e.inert), false)
  await page.locator('#open-menu').click()
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('#open-menu').evaluate(e => e === document.activeElement), true)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.locator('[data-page=inboxes]').click()
  await page.locator('#inbox-search').fill('')
  await page.locator('#inbox-group').selectOption('')

  // The selected reader inbox is Agent 1; deletion from Agent 2's row must target Agent 2.
  const target = inboxes[1].inboxId, summary = page.getByLabel(`Options for ${target}`, { exact: true })
  const openDeletion = async () => { await summary.click(); await summary.locator('..').getByRole('button', { name: 'Delete inbox…', exact: true }).click() }
  let requests = 0, mode = 'fail', resolveRequested
  const pending = new Promise(resolve => { release = resolve })
  const requested = new Promise(resolve => { resolveRequested = resolve })
  await page.route('**/api/rpc/deleteInbox', async route => {
    requests++; assert.equal(route.request().postDataJSON().inboxId, target)
    if (mode === 'fail') await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Fixture deletion unavailable' }) })
    else { resolveRequested(); await pending; await route.continue() }
  })
  await openDeletion()
  assert.equal(await page.locator('#delete-inbox-address').textContent(), target)
  assert.equal(await page.locator('#cancel-delete-inbox').evaluate(e => e === document.activeElement), true)
  await page.keyboard.press('Escape')
  await page.waitForFunction(() => !document.querySelector('#delete-inbox-dialog').open)
  assert.equal(requests, 0)
  await page.waitForFunction(label => document.activeElement?.getAttribute('aria-label') === label, `Options for ${target}`)
  await openDeletion(); await page.locator('#cancel-delete-inbox').click(); assert.equal(requests, 0)
  await openDeletion(); await page.locator('#confirm-delete-inbox').click()
  await page.getByText('Fixture deletion unavailable', { exact: true }).waitFor()
  assert.equal(await summary.count(), 1)
  mode = 'pass'; await page.locator('#confirm-delete-inbox').click(); await requested
  assert.equal(await page.locator('#confirm-delete-inbox').isDisabled(), true)
  assert.equal(await page.locator('#cancel-delete-inbox').isDisabled(), true)
  await page.locator('#delete-inbox-form').evaluate(form => form.requestSubmit())
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('#delete-inbox-dialog').isVisible(), true)
  assert.equal(requests, 2, 'Double submission does not send another deletion')
  release()
  await page.getByText('Inbox deleted', { exact: true }).waitFor()
  await page.waitForFunction(() => document.querySelector('#inbox-count').textContent === '11 inboxes')
  const remaining = (await (await api('listInboxes')).json()).result.inboxes
  assert.equal(remaining.some(inbox => inbox.inboxId === target), false)
  assert.equal(remaining.some(inbox => inbox.inboxId === inboxes[0].inboxId), true)
  assert.equal(requests, 2)
  await page.goto(base + '/app#/inboxes/' + encodeURIComponent(target))
  await page.waitForURL('**/app#/inboxes')
  await page.locator('#inboxes-page').waitFor()
  await page.unroute('**/api/rpc/deleteInbox')
  for (const inbox of remaining.slice(1)) assert.equal((await api('deleteInbox', { inboxId: inbox.inboxId })).status(), 200)
  await page.locator('#refresh-inboxes').click()
  await page.waitForFunction(() => document.querySelector('#inbox-count').textContent === '1 inbox')
  await page.locator('#inbox-rows a').click()
  await page.locator('#mail-page').waitFor()
  await page.setViewportSize({ width: 320, height: 844 })
  await page.locator('#mail-actions summary').click()
  const bounds = await page.locator('#mail-actions .actions-popover').boundingBox()
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 320, 'Inbox menu stays inside the mobile viewport')
  await page.locator('#delete-inbox').click()
  await page.locator('#confirm-delete-inbox').click()
  await page.waitForFunction(() => document.querySelector('#inbox-count').textContent === '0 inboxes')
  await page.getByRole('heading', { name: 'Create your first inbox', exact: true }).waitFor()
  assert.equal(await page.locator('#delete-inbox').isVisible(), false)
  await page.locator('#inboxes-empty').getByRole('button', { name: 'Create inbox' }).click()
  await page.locator('#inbox-dialog').waitFor()
  assert.deepEqual(errors, [])
})
